Repository stanford-centaur/smt-switch, pull requests merged in 2020-12, with the labels that each got.

#137 Fix get_cvc4_term
  cvc4/include/cvc4_term.h
Labels: simple

#131 Check sortedness in SubstitutionWalker
  src/substitution_walker.cpp
  tests/unit/unit-substitute.cpp
Labels: simple

#133 Finish old rename SortCon -> SortKind
  include/sort.h
  src/logging_sort.cpp
  src/sort.cpp
Labels: refactor

#138 Repack msat static lib by adding to libmathsat
  msat/CMakeLists.txt
Labels: simple

#140 unsatcore-reducer returns a boolean
  include/utils.h
  src/utils.cpp
Labels: simple

#139 Add get_sequence_interpolants function for interpolating solvers
  include/solver.h
  msat/include/msat_solver.h
  msat/src/msat_solver.cpp
  src/solver.cpp
  tests/test_itp.cpp
Labels: enhancement

#141 Remove Iff -- not in smt-lib standard
  btor/src/boolector_solver.cpp
  cvc4/src/cvc4_solver.cpp
  include/ops.h
  msat/src/msat_solver.cpp
  msat/src/msat_term.cpp
  python/enums_dec.pxi
  python/enums_imp.pxi
  src/ops.cpp
  src/sort_inference.cpp
  src/term_translator.cpp
  tests/yices2/yices2-gtest.cpp
  yices2/src/yices2_solver.cpp
Labels: simple

#142 Allow getting uf sort from boolector term
  btor/include/boolector_sort.h
  btor/src/boolector_sort.cpp
  btor/src/boolector_term.cpp
  tests/unit/unit-sort.cpp
Labels: simple

#144 Allow creating a MsatSolver from a msat_config and msat_env directly
  msat/include/msat_solver.h
Labels: simple

#143 Move constant strings for printing solver to utils
  CMakeLists.txt
  include/smtlib_utils.h
  src/printing_solver.cpp
Labels: simple

#145 Changing SMT-LIB constants to strings instead of macros
  include/smtlib_utils.h
Labels: simple

#149 Add method to get unique Term ID
  btor/include/boolector_term.h
  btor/src/boolector_term.cpp
  cvc4/include/cvc4_term.h
  cvc4/src/cvc4_term.cpp
  include/logging_solver.h
  include/logging_term.h
  include/term.h
  msat/include/msat_term.h
  msat/src/msat_term.cpp
  src/logging_solver.cpp
  src/logging_term.cpp
  src/term.cpp
  tests/CMakeLists.txt
  tests/unit/unit-term-id.cpp
  yices2/include/yices2_term.h
  yices2/src/yices2_term.cpp
Labels: simple
